plugins {
    id 'com.android.application'
}

android {
    namespace 'in.vkvnalbari.vkvtt'
    compileSdk 35

    defaultConfig {
        applicationId 'in.vkvnalbari.vkvtt'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '1.0.1'
    }
}

dependencies {
    implementation 'androidx.browser:browser:1.8.0'
}
